version: 2
defaults: &defaults
  working_directory: ~/project/portal-vue
  docker:
    - image: circleci/node:12.19.0
jobs:
  install_deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install npm dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - portal-vue

  build_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Build release files
          command: yarn lib:build

  exec_unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Unit Tests
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build_release:
          requires:
            - install_deps
          filters:
            branches:
              only:
                - next
                - develop
                - master
      - exec_unit_tests:
          requires:
            - install_deps
